import 'dart:developer';
import 'dart:math' as math;

import 'package:eb_delegate/eb_delegate.dart';
import 'package:eb_home_feature/eb_home_feature.dart';
import 'package:eb_uikit/eb_uikit.dart';
import 'package:eb_resource/eb_resource.dart';
import 'package:eb_add_schedule/eb_add_schedule.dart';
import 'package:eb_state/eb_state.dart';
import 'package:eb_event/eb_event.dart';
import 'package:eb_model/eb_model.dart';
import 'package:flutter/cupertino.dart';
import 'package:eb_find_route/eb_find_route.dart';
import 'package:eb_search_place/eb_search_place.dart';
import 'package:flutter/foundation.dart';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:eb_repository_interface/eb_repository_interface.dart';
import 'package:intl/intl.dart';
import 'package:modal_bottom_sheet/modal_bottom_sheet.dart';

part 'sources/home_view.dart';
part 'sources/calendar_view/home_calendar.dart';
part 'sources/calendar_view/home_calendar_header.dart';
part 'sources/top_schedule_info/top_schedule_info.dart';
part 'sources/top_schedule_info/none_top_schedule_info.dart';
part 'sources/top_schedule_info/today_top_schedule_info.dart';
part 'sources/middle_transport/cards/middle_transport_card_form.dart';
part 'sources/home_content/schedule_addbutton.dart';
part 'sources/bottom_list_view/home_bottom_schedule_card.dart';
part 'sources/bottom_list_view/home_bottom_list_view.dart';
part 'sources/home_content/home_appbar.dart';
part 'sources/home_content/home_content.dart';
part 'sources/middle_transport/cards/add/middle_transport_add.dart';
part 'sources/middle_transport/middle_transport_view.dart';
part 'sources/middle_transport/cards/info/transport_info/middle_transport_info_view.dart';
part 'sources/middle_transport/cards/info/transport_info/middle_transport_info_card_scale.dart';
part 'sources/middle_transport/cards/info/transport_info/middle_transport_info_card.dart';
part 'sources/middle_transport/cards/info/transport_info/left_dispatch/left_dispatch_column.dart';
part 'sources/middle_transport/cards/info/transport_info/left_dispatch/left_dispatch_column_content.dart';
part 'sources/middle_transport/cards/info/transport_info/left_dispatch/left_dispatch_popup_button.dart';
part 'sources/middle_transport/cards/info/transport_info/right_dispatch/right_dispatch_column.dart';
part 'sources/middle_transport/cards/info/transport_info/right_dispatch/reload_trasnport_info_button.dart';
part 'sources/middle_transport/cards/info/imminent/middle_transport_imminent.dart';
