name: earlybuddy

packages:
  - presentation/**
  - domain/**
  - core/**
  - shared/**
  - app/**

command:
  bootstrap:
    environment:
      sdk: ^3.5.0
      flutter: ">=1.17.0"
    dev_dependencies:
      flutter_oss_licenses: ^3.0.4
    dependencies:
      flutter_localizations:
        sdk: flutter
      cupertino_icons: ^1.0.6
      table_calendar: ^3.1.0
      intl: ^0.19.0
      equatable: ^2.0.5
      flutter_bloc: ^8.1.6
      dio: ^5.4.2+1
      modal_bottom_sheet: ^3.0.0
      kakao_map_plugin: ^0.3.0
      flutter_dotenv: ^5.1.0
      stream_transform: ^2.1.0
      geolocator: ^11.0.0
      flutter_secure_storage: ^9.2.2
      rxdart: ^0.28.0
      introduction_screen: ^3.1.14
      flutter_native_splash: ^2.4.1
      shared_preferences: ^2.3.2
      lottie: ^3.1.2
      flutter_launcher_icons: ^0.14.1
      flutter_local_notifications: ^18.0.1
      firebase_messaging: ^15.1.5
      firebase_core: ^3.8.0

scripts:
  test_all:
    # Only run the test command when the package has a test directory
    run: flutter test
    exec:
      concurrency: 1
    packageFilters:
      flutter: true
      dirExists: test
    description: Run `flutter test` in all targets