// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhPcFeZTPa_1qgRrh-OTpGvywEniiXUE',
    appId: '1:280836859349:web:fb4bd08bc7adbaef82095c',
    messagingSenderId: '280836859349',
    projectId: 'earlybuddy-63514',
    authDomain: 'earlybuddy-63514.firebaseapp.com',
    storageBucket: 'earlybuddy-63514.firebasestorage.app',
    measurementId: 'G-CCKBFNVE3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhEqgks5dmRXYR8MaKCHDQlcLaSoOBceg',
    appId: '1:280836859349:android:aaacf629ec76bb8e82095c',
    messagingSenderId: '280836859349',
    projectId: 'earlybuddy-63514',
    storageBucket: 'earlybuddy-63514.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnWcpxcqeHBmZrm10rZy8aJuctC1E49ew',
    appId: '1:280836859349:ios:60c8f1b80b46ce2c82095c',
    messagingSenderId: '280836859349',
    projectId: 'earlybuddy-63514',
    storageBucket: 'earlybuddy-63514.firebasestorage.app',
    iosBundleId: 'com.earlybuddy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnWcpxcqeHBmZrm10rZy8aJuctC1E49ew',
    appId: '1:280836859349:ios:68e44283ca42c01582095c',
    messagingSenderId: '280836859349',
    projectId: 'earlybuddy-63514',
    storageBucket: 'earlybuddy-63514.firebasestorage.app',
    iosBundleId: 'com.earlybuddy.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVhPcFeZTPa_1qgRrh-OTpGvywEniiXUE',
    appId: '1:280836859349:web:f23e80b64ccd8d1882095c',
    messagingSenderId: '280836859349',
    projectId: 'earlybuddy-63514',
    authDomain: 'earlybuddy-63514.firebaseapp.com',
    storageBucket: 'earlybuddy-63514.firebasestorage.app',
    measurementId: 'G-HHF3YR4NG1',
  );
}
